### ISSUE TITLE
Functionality Questions

### ISSUE THREAD

**Issue by ZKing1000** [instabotai/instabotai#14]
I originally sent this message to brominercom@gmail.com, which is linked on your site.

Hello, I am a user of InstaPy (@ZKing1000 on github). I have talked to @reliefs.
I have a couple bots currently, which point to my two main instagram profiles. They simply follow users randomly from the following lists of accounts of my precompiled list (about 100 hand picked accounts) and sometimes like posts.

I would like to extend my networks functionality to more bots which are aware of the following of other bots, as to avoid repeat following people; I am also very interested in your story watching functionality and more.

We have talked about contributions in the past; I am interested in the direction of the project, particularly considering the requested functionality.

Thx!

**Comment by reliefs** [comment]
Hi ZKing1000,

You can see the direction of the project right here:
https://github.com/instabotai/instabotai/projects/2

My overall 6 months goal is right here:
https://github.com/users/reliefs/projects/1

Right now i am building a GUI and starts to accept funding for this project, I will make a paid version with the GUI. To extend the bot and overall project.
