### ISSUE TITLE
challenge required on starting bot.

### ISSUE THREAD

**Issue by reliefs** [instabotai/instabotai#27]
Some users also get challenge required when starting the bot, somehow the bot does not redirect.. 70% of web users are affected.

**Comment by reliefs** [comment]
Do you get challenge required on login ?

If so and the bot does not start on clicking start, do you get redirected to challenge page ?

**Comment by dizzy1bizzy** [comment]
yes as soon as i choose the profile to login i get challenge question once i input challenge answer it does not start the flask instance and i just attempt to restart run.py and get the same challenge again.
