### ISSUE TITLE
syntax error run.py

### ISSUE THREAD

**Issue by rain82k** [instabotai/instabotai#29]
I become this error on start instabotai

```
sudo python run.py -u NAME -p PASS 
  File "run.py", line 72
    return print(str(yz))
               ^
SyntaxError: invalid syntax
```

run on a VM with Unbutu

**Comment by reliefs** [comment]
what python version?

We do recommend python 64 bit version 3.7.

If you have another version try to install that one or real README.md at the buttom.

**Comment by rain82k** [comment]
Python 3.7.3 is installed. 

If I start the script like this

python3 run.py -u USER -p PASS

this error appears: Invalid machine command (memory dump written)

**Comment by reliefs** [comment]
issue fixed ?

**Comment by rain82k** [comment]
Hello, I am sorry that I am only answering but I was just on vacation. I suppose that's because of the hardware, because the script is running on my Debian root server but not on my virtual machine with Debian on my Synology DS916 +.

Best Greetz
Am 17. Sept. 2019, 15:44 +0200 schrieb Steffan Jensen <notifications@github.com>:
