### ISSUE TITLE
Instabot's LICENCE agreement

### ISSUE THREAD

**Issue by ohld** [instabotai/instabotai#31]
Hi. Since you are using the Instabot sources in your project, you have to follow it's [LICENCE](https://github.com/instagrambot/instabot/blob/master/LICENSE) agreement which states that you can use and modify the sources only if a copy of the licence and copyright notice are included with the software and all changes made to the code are documented.

Please provide the link to [Instabot project](https://github.com/instagrambot/instabot) in [Readme.md](https://github.com/instabotai/instabotai/blob/master/README.md) file and upload the original [LICENCE](https://github.com/instagrambot/instabot/blob/master/LICENSE) file to instabot folder.

**Comment by madshansens** [comment]
it's all online on github so i don't know what the fuss are about ?

Den søn. 15. dec. 2019 kl. 23.15 skrev Daniil Okhlopkov <
notifications@github.com>:
