### ISSUE TITLE
Just Chill

### ISSUE THREAD

**Issue by Ygohel18** [instabotai/instabotai#34]
They only stole your code cause they can't do this.

**Comment by arieller** [comment]
"Just Chill" - the most unchilling thing you can say to a tilted bro

**Comment by steffanjensen** [comment]
I made $50 on this project in 10 months, it was resold over 10.000 times by other devs.. I am not going to update this again, waste of my time making others rich while i myself is poor.

**Comment by Ygohel18** [comment]
I also developed Instagram bot not with API but with selenium in python.

As your code is misused by some fucking guys.

do not upload my code on GitHub instead I am making its GUI version and purchasing domain to provide this Instagram automation service to end-user

you should delete this repo. permeant and top any further misuse of it.

☺
