### ISSUE TITLE
ModuleNotFoundError: No module named 'flask'

### ISSUE THREAD

**Issue by Mormia** [instabotai/instabotai#7]
I really doesnt understand those things i just watch some youtube videos and trying to be get some followers when i run script i get this error

**Comment by Mormia** [comment]
Okay i did "pip install flask" now i get this error 

  **** from flask import Flask, template, request
ImportError: cannot import name 'template' from 'flask' (C:\Users\Mia\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\__init__.py)### ****

**Comment by reliefs** [comment]
Is it still an issue ?
Will update new build tonight.

Do to install with your current build.
pip install -r requirements.txt
